// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcCqu5ANaHFd0NgtzuCf19xlkq362zvPI',
    appId: '1:810843615994:web:7603fedd0034dcc7784f43',
    messagingSenderId: '810843615994',
    projectId: 'ek-pal',
    authDomain: 'ek-pal.firebaseapp.com',
    storageBucket: 'ek-pal.appspot.com',
    measurementId: 'G-TQ3HY52W0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaN-4jyrXftil-6a7X1XQBuTzw0UTVjg',
    appId: '1:810843615994:android:6fa8e7938d5f5117784f43',
    messagingSenderId: '810843615994',
    projectId: 'ek-pal',
    storageBucket: 'ek-pal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCmaaVfSvOHOZjZEIdWht60xBPC066pSo',
    appId: '1:810843615994:ios:9a58135e14a65610784f43',
    messagingSenderId: '810843615994',
    projectId: 'ek-pal',
    storageBucket: 'ek-pal.appspot.com',
    iosClientId: '810843615994-rbjgjk0dfbl3c900l58icesvaenm0ilk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCmaaVfSvOHOZjZEIdWht60xBPC066pSo',
    appId: '1:810843615994:ios:9a58135e14a65610784f43',
    messagingSenderId: '810843615994',
    projectId: 'ek-pal',
    storageBucket: 'ek-pal.appspot.com',
    iosClientId: '810843615994-rbjgjk0dfbl3c900l58icesvaenm0ilk.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );
}
